using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DinoController : MonoBehaviour
{
    public static DinoController instance; //НЬБлХц
    public float moveSpeedZ; //zУр ПђСїРЬДТ МгЕЕ КЏМі
    public float moveSpeedX; //xУр ПђСїРЬДТ МгЕЕ КЏМі

    //БИУМРЧ СпНЩРЬ ЕЩ РЇФЁ
    public Vector3 sphereCenter;

    //БИУМРЧ ЙнСіИЇ
    public float sphereRadius = 0.5f;

    public DinoPositionController dinoPositionController;

    private void Awake() //НЬБлХц
    {
        if (instance != null)
        {
            Destroy(this.gameObject);
        }
        else
        {
            instance = this;
        }
    }
    void Start()
    {
        
    }
    void Update()
    {
        if (GameManager.instance.isGameStart == true)
        {
            DinoMove(); // (alt + enterХА ИоМ­Ех УпУт -> ЧдМі ИИЕщОюСм)
            DoorCheck();
        }
    }

    private void DinoMove()
    {
        //trnaform.Translate(0,0,moveSpeedZ);
        transform.position += Vector3.forward * Time.deltaTime * moveSpeedZ;
        if (Input.GetKey(KeyCode.RightArrow))
        {
            //transform.position += Vector3.right * Time.deltaTime ;
            transform.Translate(moveSpeedX * Time.deltaTime, 0, 0);
        }
        if (Input.GetKey(KeyCode.LeftArrow))
        {
            // transform.position += Vector3.left * Time.deltaTime;
            transform.Translate(-moveSpeedX * Time.deltaTime, 0, 0);
        }
        //АјЗц ПђСїРЬДТ ЙќРЇ[1]
        transform.position = new Vector3(Mathf.Clamp(transform.position.x, -3.9f, 3.9f), transform.position.y, transform.position.z);

        //АјЗц ПђСїРЬДТ ЙќРЇ ЙцЙ§[2]
        //if(transform.position.x >-3.9f)
        //{
        //    if (Input.GetKey(KeyCode.RightArrow))
        //    {
        //        transform.Translate(moveSpeedX * Time.deltaTime, 0, 0);
        //    }
        //}
        //if (transform.position.x > -3.9f)
        //{
        //    if (Input.GetKey(KeyCode.LeftArrow))
        //    {
        //        transform.Translate(-moveSpeedX * Time.deltaTime, 0, 0);
        //    }
        //}
    }
    void DoorCheck()
    {
        //БИУМ ПЕПЊ ГЛРЧ ColliderЕщРЛ АЈСі
        Collider[] hitColliders = Physics.OverlapSphere(transform.position + sphereCenter, sphereRadius);

        //АЈСіЕШ colliderЕщ УГИЎ
        foreach(Collider doors in hitColliders)
        {
            if (doors.CompareTag("Goal"))
            {
                //GoalРЮ СіСЁПЁ ДъОвРЛ ЖЇ
                Debug.Log("АёРЮ!");
                //УцЕЙЧб ПРКъСЇЦЎРЧ BoxcolliderФФЦїГЭЦЎИІ КёШАМКШ­ ЧиСм
                doors.gameObject.GetComponent<BoxCollider>().enabled = false;
            }
            else
            {
                //Debug.Log("АЈСіЕШ ПРКъСЇЦЎ" + doors.gameObject.name);
                //ПЉБтПЁМ­ УцЕЙЧб DoorРЧ ХИРдАњ ЙЎПЁ НсСј М§РкИІ ЙоОЦПЭМ­
                int doorNumber = doors.gameObject.GetComponent<SelectDoors>().GetDoorNumber(transform.position.x);
                DoorType doorType = doors.gameObject.GetComponent<SelectDoors>().GetDoorType(transform.position.x);

                //УцЕЙЧб ПРКъСЇЦЎРЧ BoxcolliderФФЦїГЭЦЎИІ КёШАМКШ­ ЧиСм
                doors.gameObject.GetComponent<BoxCollider>().enabled = false;

                //DionPositioncontroller НКХЉИГЦЎПЁМ­ РћР§ЧЯАд ЛчФЂПЌЛъПЁ ИТАд АшЛъЧиМ­ RapotorЕщРЛ ДУРЬАХГЊ СйРЬИщ ЕЩАХ ААРН.
                dinoPositionController.SetDoorcalc(doorType, doorNumber);
            }
            
        }
    }

    //БИУМ ПЕПЊРЛ GizmoЗЮ НУАЂШ­
     void OnDrawGizmos()
    {
        Gizmos.color = Color.red;
        Gizmos.DrawWireSphere(transform.position + sphereCenter, sphereRadius);
    }
    public float GetDinoDistance()
    {
        return dinoPositionController.transform.position.z;
    }
}
